{
  if (throwable instanceof InvocationTargetException)   throwable=throwable.getCause();
  return new RuntimeException(wrapException(throwable));
}
