{
  if (throwable instanceof AssertionError) {
    doAddFailure(test,(Error)throwable);
  }
 else {
    stopMeter(test);
    prepareDefectPacket(test,throwable).send();
  }
}
