{
  try {
    super.dispatchEvent(e);
  }
 catch (  ProcessCanceledException pce) {
    throw pce;
  }
catch (  Throwable exc) {
    LOG.error("Error during dispatching of " + e,exc);
  }
}
