{
  try {
    i=5;
  }
  finally {
    throw new Exception();
  }
}
