{
  try {
    root.getEntry("unknown entry");
    fail();
  }
 catch (  RuntimeException e) {
    assertEquals("entry 'unknown entry' not found",e.getMessage());
  }
  try {
    root.getEntry(42);
    fail();
  }
 catch (  RuntimeException e) {
    assertEquals("entry #42 not found",e.getMessage());
  }
}
