{
  try {
    return method.invoke(object,args);
  }
 catch (  IllegalAccessException e) {
    throw new RuntimeException(e);
  }
catch (  InvocationTargetException e) {
    final Throwable cause=e.getCause();
    if (cause instanceof ProcessCanceledException) {
      throw (ProcessCanceledException)cause;
    }
    throw new RuntimeException(e);
  }
}
