{
  try {
    doRun(indicator);
  }
 catch (  Exception e) {
    LOG.info("Unexpected exception occurred during reformatting file " + myFile,e);
  }
}
