{
  try {
    return doGetRecordsCount();
  }
 catch (  IOException e) {
    throw new AssertionError(e);
  }
}
