{
  try {
    DoJob();
  }
 catch (  RuntimeException e) {
    if (e.getCause() == null || !(e.getCause() instanceof InterruptedException))     throw e;
  }
catch (  Exception e) {
  }
}
