{
  try {
    doTestExistingClass("Param","");
  }
 catch (  Exception e) {
    e.printStackTrace();
    return;
  }
  fail("Conflic was not found");
}
