{
  try {
    doTestExistingClass("Integer","java.lang");
  }
 catch (  Exception e) {
    e.printStackTrace();
    return;
  }
  fail("Conflict was not found");
}
