{
  if (t instanceof ProcessCanceledException) {
    myLogger.error(new Throwable("Do not log ProcessCanceledException").initCause(t));
    throw (ProcessCanceledException)t;
  }
  if (t != null && t.getClass().getName().contains("ReparsedSuccessfullyException")) {
    myLogger.error(new Throwable("Do not log ReparsedSuccessfullyException").initCause(t));
    throw (RuntimeException)t;
  }
  String detailString=StringUtil.join(details,"\n");
  if (ourErrorsOccurred == null) {
    String s=message != null && !message.isEmpty() ? "Error message is '" + message + "'" : "";
    String mess="Logger errors occurred. See IDEA logs for details. " + s;
    ourErrorsOccurred=new Exception(mess + (!detailString.isEmpty() ? "\nDetails: " + detailString : ""),t);
  }
  myLogger.error(message + (!detailString.isEmpty() ? "\nDetails: " + detailString : ""),t);
  logErrorHeader();
  if (t != null && t.getCause() != null) {
    myLogger.error("Original exception: ",t.getCause());
  }
}
