def rollback(self):
    wlock = lock = None
    try:
        wlock = self.wlock()
        lock = self.lock()
        if os.path.exists(self.sjoin('undo')):
            self.ui.status(_('rolling back last transaction\n'))
            transaction.rollback(self.sopener, self.sjoin('undo'), self.ui.warn)
            util.rename(self.join('undo.dirstate'), self.join('dirstate'))
            try:
                branch = self.opener('undo.branch').read()
                self.dirstate.setbranch(branch)
            except IOError:
                self.ui.warn((_('Named branch could not be reset, current branch still is: %s\n') % encoding.tolocal(self.dirstate.branch())))
            self.invalidate()
            self.dirstate.invalidate()
            self.destroyed()
        else:
            self.ui.warn(_('no rollback information available\n'))
    finally:
        release(lock, wlock)
