{
  String expectedError=null;
  try {
    doExitPointsTest(false);
  }
 catch (  PrepareFailedException ex) {
    expectedError=ex.getMessage();
  }
  assertEquals(expectedMessage,expectedError);
}
