{
  try {
    doRun();
  }
 catch (  RuntimeException|Error e) {
    saveException(e,myUpdateProgress);
    throw e;
  }
}
