{
  try {
  }
 catch (  MyException<caret> e) {
  }
}
